Repository kubernetes-sigs/network-policy-api, pull requests merged in 2023-05, with the labels that each got.

#75 Fix description for same/notSameLabels; remove NamespaceRelation
  apis/v1alpha1/shared_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/policy.networking.k8s.io_adminnetworkpolicies.yaml
  config/crd/bases/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#97 remove unactive code owners
  OWNERS
Labels: cncf-cla: yes, approved, lgtm, size/XS

#98 Add Framework for Conformance Tests
  Makefile
  conformance/base/manifests.yaml
  conformance/conformance_test.go
  conformance/embed.go
  conformance/tests/main.go
  conformance/utils/config/timeout.go
  conformance/utils/flags/flag.go
  conformance/utils/kubernetes/apply.go
  conformance/utils/kubernetes/apply_test.go
  conformance/utils/kubernetes/helper.go
  conformance/utils/suite/features.go
  conformance/utils/suite/suite.go
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#99 Add ANP conformance tests for `.Spec.Ingress` and `.Spec.Egress` fields
  conformance/tests/admin-network-policy-core-egress-sctp-rules.go
  conformance/tests/admin-network-policy-core-egress-sctp-rules_base.yaml
  conformance/tests/admin-network-policy-core-egress-tcp-rules.go
  conformance/tests/admin-network-policy-core-egress-tcp-rules_base.yaml
  conformance/tests/admin-network-policy-core-egress-udp-rules.go
  conformance/tests/admin-network-policy-core-egress-udp-rules_base.yaml
  conformance/tests/admin-network-policy-core-ingress-sctp-rules.go
  conformance/tests/admin-network-policy-core-ingress-sctp-rules_base.yaml
  conformance/tests/admin-network-policy-core-ingress-tcp-rules.go
  conformance/tests/admin-network-policy-core-ingress-tcp-rules_base.yaml
  conformance/tests/admin-network-policy-core-ingress-udp-rules.go
  conformance/tests/admin-network-policy-core-ingress-udp-rules_base.yaml
  conformance/utils/kubernetes/helper.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#105 Add conformance integration tests between ANP/NP/BANP
  conformance/tests/admin-network-policy-core-integration.go
  conformance/tests/admin-network-policy-core-integration_base.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm
