Repository kubernetes-sigs/network-policy-api, pull requests merged in 2023-09, with the labels that each got.

#141 NIT: Fix sample user yamls
  site-src/user-story-examples/user-story-2.yaml
  site-src/user-story-examples/user-story-5.yaml
Labels: size/S, kind/documentation, cncf-cla: yes, approved, lgtm

#117 NPEP: Add support for egress traffic control
  npep/npep-126-egress-traffic-control.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#131 add release channels and support levels
  apis/v1alpha1/adminnetworkpolicy_types.go
  apis/v1alpha1/baselineadminnetworkpolicy_types.go
  apis/v1alpha1/shared_types.go
  config/crd/experimental/policy.networking.k8s.io_adminnetworkpolicies.yaml
  config/crd/experimental/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
  config/crd/kustomization.yaml
  config/crd/standard/policy.networking.k8s.io_adminnetworkpolicies.yaml
  config/crd/standard/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
  hack/build-install-yaml.sh
  mkdocs.yml
  pkg/generator/main.go
  site-src/conformance.md
  site-src/enhancements.md
  site-src/index.md
  site-src/versioning.md
Labels: cncf-cla: yes, approved, lgtm, size/XXL
