Repository kubernetes-sigs/network-policy-api, pull requests merged in 2023-11, with the labels that each got.

#166 Add ovnk conformance-report
  conformance/reports/v0.1.2/ovn-kubernetes.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#123 Create NPEP-122 for Tenancy API update.
  npeps/npep-122.md
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#143 Implement Cluster Egress Traffic semantics (ANP&BANP NorthBound Support) - PART1 - Nodes
  apis/v1alpha1/adminnetworkpolicy_types.go
  apis/v1alpha1/baselineadminnetworkpolicy_types.go
  apis/v1alpha1/shared_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/experimental/policy.networking.k8s.io_adminnetworkpolicies.yaml
  config/crd/experimental/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
  config/crd/standard/policy.networking.k8s.io_adminnetworkpolicies.yaml
  config/crd/standard/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm, api-review

#180 updated yaml file for latest release
  site-src/getting-started.md
Labels: kind/documentation, cncf-cla: yes, approved, lgtm, size/XS

#176 updated link for graduation criteria
  site-src/enhancements.md
Labels: kind/documentation, cncf-cla: yes, approved, lgtm, size/XS
