Repository kubernetes-sigs/network-policy-api, pull requests merged in 2024-11, with the labels that each got.

#264 [Policy Assistant] Add support for dynamic workload traffic via POLA cli
  cmd/policy-assistant/examples/traffic.json
  cmd/policy-assistant/pkg/cli/analyze.go
  cmd/policy-assistant/pkg/matcher/traffic.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#268 fix: [Policy Assistant] translate could grab labels from other pods
  .github/workflows/policy-assistant.yml
  cmd/policy-assistant/pkg/matcher/traffic.go
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#266 nitfix: KubeOVN link was wrongly populated
  site-src/implementations.md
Labels: cncf-cla: yes, approved, lgtm, size/XS

#270 chore: [Policy Assistant] lingering pola references
  cmd/policy-assistant/.github/workflows/kind_antrea.yml
  cmd/policy-assistant/.github/workflows/kind_calico.yml
  cmd/policy-assistant/.github/workflows/kind_cilium.yml
  cmd/policy-assistant/.github/workflows/kind_cni_from_source.yml
  cmd/policy-assistant/.github/workflows/kind_ovn.yml
  cmd/policy-assistant/.goreleaser.yml
  cmd/policy-assistant/Makefile
  cmd/policy-assistant/README.md
  cmd/policy-assistant/examples/run.sh
  cmd/policy-assistant/hack/sonobuoy/run-sonobuoy-plugin.sh
  cmd/policy-assistant/pkg/connectivity/probe/pod.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#271 docs: changelog for v0.0.1-policy-assistant
  cmd/policy-assistant/CHANGELOG.md
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#272 chore(goreleaser): [Policy Assistant] fix format of checksum file
  cmd/policy-assistant/.goreleaser.yml
Labels: cncf-cla: yes, approved, lgtm, size/XS, ok-to-test

#269 docs: [Policy Assistant] walkthrough demo with use cases and example files
  cmd/policy-assistant/examples/demos/walkthrough/README.md
  cmd/policy-assistant/examples/demos/walkthrough/demo-deployment-a.yaml
  cmd/policy-assistant/examples/demos/walkthrough/demo-pod-b.yaml
  cmd/policy-assistant/examples/demos/walkthrough/policies/anp1.yaml
  cmd/policy-assistant/examples/demos/walkthrough/policies/anp2.yaml
  cmd/policy-assistant/examples/demos/walkthrough/policies/banp.yaml
  cmd/policy-assistant/examples/demos/walkthrough/policies/npv1.yaml
  cmd/policy-assistant/examples/demos/walkthrough/traffic.json
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#265 KANP is now available in Calico
  site-src/implementations.md
Labels: cncf-cla: yes, approved, lgtm, size/XS, ok-to-test

#256 Bump to 1.31.2 kube
  .github/workflows/conformance.yml
  apis/v1alpha1/shared_types.go
  config/crd/experimental/policy.networking.k8s.io_adminnetworkpolicies.yaml
  config/crd/experimental/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
  config/crd/standard/policy.networking.k8s.io_adminnetworkpolicies.yaml
  config/crd/standard/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
  go.mod
  go.sum
  hack/crd-e2e.sh
  pkg/client/applyconfiguration/apis/v1alpha1/adminnetworkpolicy.go
  pkg/client/applyconfiguration/apis/v1alpha1/adminnetworkpolicyegresspeer.go
  pkg/client/applyconfiguration/apis/v1alpha1/adminnetworkpolicyegressrule.go
  pkg/client/applyconfiguration/apis/v1alpha1/adminnetworkpolicyingresspeer.go
  pkg/client/applyconfiguration/apis/v1alpha1/adminnetworkpolicyingressrule.go
  pkg/client/applyconfiguration/apis/v1alpha1/adminnetworkpolicyport.go
  pkg/client/applyconfiguration/apis/v1alpha1/adminnetworkpolicyspec.go
  pkg/client/applyconfiguration/apis/v1alpha1/adminnetworkpolicystatus.go
  pkg/client/applyconfiguration/apis/v1alpha1/adminnetworkpolicysubject.go
  pkg/client/applyconfiguration/apis/v1alpha1/baselineadminnetworkpolicy.go
  pkg/client/applyconfiguration/apis/v1alpha1/baselineadminnetworkpolicyegresspeer.go
  pkg/client/applyconfiguration/apis/v1alpha1/baselineadminnetworkpolicyegressrule.go
  pkg/client/applyconfiguration/apis/v1alpha1/baselineadminnetworkpolicyingressrule.go
  pkg/client/applyconfiguration/apis/v1alpha1/baselineadminnetworkpolicyspec.go
  pkg/client/applyconfiguration/apis/v1alpha1/baselineadminnetworkpolicystatus.go
  pkg/client/applyconfiguration/apis/v1alpha1/namespacedpod.go
  pkg/client/applyconfiguration/apis/v1alpha1/port.go
  pkg/client/applyconfiguration/apis/v1alpha1/portrange.go
  pkg/client/applyconfiguration/utils.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/adminnetworkpolicy.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/baselineadminnetworkpolicy.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/fake/fake_adminnetworkpolicy.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/fake/fake_baselineadminnetworkpolicy.go
  pkg/client/listers/apis/v1alpha1/adminnetworkpolicy.go
  pkg/client/listers/apis/v1alpha1/baselineadminnetworkpolicy.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#277 Fix github repo name in .goreleaser.yml
  cmd/policy-assistant/.goreleaser.yml
Labels: cncf-cla: yes, approved, lgtm, size/XS, ok-to-test
