Repository kubernetes-sigs/network-policy-api, pull requests merged in 2024-05, with the labels that each got.

#228 fixup deps for the website
  requirements.txt
Labels: cncf-cla: yes, approved, lgtm, size/XS

#200 Add API spec for FQDN selector
  mkdocs.yml
  npeps/npep-133-fqdn-egress-selector.md
  npeps/npep-133.md
Labels: cncf-cla: yes, approved, size/XL, lgtm, ok-to-test

#229 Update the text about duplicate priority values
  apis/v1alpha1/adminnetworkpolicy_types.go
  config/crd/experimental/policy.networking.k8s.io_adminnetworkpolicies.yaml
  config/crd/standard/policy.networking.k8s.io_adminnetworkpolicies.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm
