Repository kubernetes-sigs/network-policy-api, pull requests merged in 2024-07, with the labels that each got.

#237 Update implementations.md
  site-src/implementations.md
Labels: cncf-cla: yes, approved, lgtm, size/XS

#227 [Policy Assistant] Add support for k8s native workload traffic
  cmd/policy-assistant/pkg/kube/kubernetes.go
  cmd/policy-assistant/pkg/matcher/traffic.go
  cmd/policy-assistant/test/workloadTraffic/getDaemonSetsOutput.json
  cmd/policy-assistant/test/workloadTraffic/getDeploymentsOutput.json
  cmd/policy-assistant/test/workloadTraffic/getPodsOutput.json
  cmd/policy-assistant/test/workloadTraffic/getReplicaSetsOutput.json
  cmd/policy-assistant/test/workloadTraffic/getStatefulSetsOutput.json
  cmd/policy-assistant/test/workloadTraffic/workload-traffic-output.json
  cmd/policy-assistant/test/workloadTraffic/workload-traffic.json
  cmd/policy-assistant/test/workloadTraffic/workloads/daemonSet.yaml
  cmd/policy-assistant/test/workloadTraffic/workloads/deployment.yaml
  cmd/policy-assistant/test/workloadTraffic/workloads/pod.yaml
  cmd/policy-assistant/test/workloadTraffic/workloads/replicaSet.yaml
  cmd/policy-assistant/test/workloadTraffic/workloads/statefulSet.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XXL, ok-to-test

#240 [Policy Assistant] fix: npv1 deny-all simulation
  cmd/policy-assistant/pkg/matcher/builder.go
  cmd/policy-assistant/pkg/matcher/explain.go
  cmd/policy-assistant/pkg/matcher/peermatcher.go
  cmd/policy-assistant/pkg/matcher/simplifier.go
  cmd/policy-assistant/pkg/matcher/simplifier_tests.go
  cmd/policy-assistant/test/integration/integration_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#243 [Policy Assistant] fix: compile error introduced by #241
  cmd/policy-assistant/pkg/matcher/builder.go
Labels: cncf-cla: yes, approved, lgtm, size/XS
