Repository kubernetes-sigs/network-policy-api, pull requests merged in 2024-04, with the labels that each got.

#214 Fix tests to reflect newAPI changes
  conformance/base/admin_network_policy/core-egress-sctp-rules.yaml
  conformance/base/admin_network_policy/core-egress-tcp-rules.yaml
  conformance/base/admin_network_policy/core-egress-udp-rules.yaml
  conformance/base/admin_network_policy/core-gress-rules-combined.yaml
  conformance/base/admin_network_policy/core-ingress-sctp-rules.yaml
  conformance/base/admin_network_policy/core-ingress-tcp-rules.yaml
  conformance/base/admin_network_policy/core-ingress-udp-rules.yaml
  conformance/base/admin_network_policy/core-priority-field.yaml
  conformance/base/admin_network_policy/extended-egress-selector-rules.yaml
  conformance/base/api_integration/core-anp-np-banp.yaml
  conformance/base/baseline_admin_network_policy/core-egress-sctp-rules.yaml
  conformance/base/baseline_admin_network_policy/core-egress-tcp-rules.yaml
  conformance/base/baseline_admin_network_policy/core-egress-udp-rules.yaml
  conformance/base/baseline_admin_network_policy/core-gress-rules-combined.yaml
  conformance/base/baseline_admin_network_policy/core-ingress-sctp-rules.yaml
  conformance/base/baseline_admin_network_policy/core-ingress-tcp-rules.yaml
  conformance/base/baseline_admin_network_policy/core-ingress-udp-rules.yaml
Labels: cncf-cla: yes, approved, size/XL, lgtm

#217 Change udp port listeners on host-net pods
  conformance/base/admin_network_policy/extended-egress-selector-rules.yaml
  conformance/base/manifests.yaml
  conformance/tests/admin-network-policy-extended-egress-rules.go
  conformance/tests/baseline-admin-network-policy-extended-egress-rules.go
Labels: cncf-cla: yes, size/L, approved, lgtm, area/conformance

#218 Do patch instead of update
  conformance/tests/admin-network-policy-core-egress-sctp-rules.go
  conformance/tests/admin-network-policy-core-egress-tcp-rules.go
  conformance/tests/admin-network-policy-core-egress-udp-rules.go
  conformance/tests/admin-network-policy-core-gress-rules.go
  conformance/tests/admin-network-policy-core-ingress-sctp-rules.go
  conformance/tests/admin-network-policy-core-ingress-tcp-rules.go
  conformance/tests/admin-network-policy-core-ingress-udp-rules.go
  conformance/tests/admin-network-policy-core-integration.go
  conformance/tests/admin-network-policy-core-priority.go
  conformance/tests/admin-network-policy-extended-egress-rules.go
  conformance/tests/admin-network-policy-extended-ingress-rules.go
  conformance/tests/baseline-admin-network-policy-core-egress-sctp-rules.go
  conformance/tests/baseline-admin-network-policy-core-egress-tcp-rules.go
  conformance/tests/baseline-admin-network-policy-core-egress-udp-rules.go
  conformance/tests/baseline-admin-network-policy-core-gress-rules.go
  conformance/tests/baseline-admin-network-policy-core-ingress-sctp-rules.go
  conformance/tests/baseline-admin-network-policy-core-ingress-tcp-rules.go
  conformance/tests/baseline-admin-network-policy-core-ingress-udp-rules.go
  conformance/tests/baseline-admin-network-policy-extended-egress-rules.go
  conformance/tests/baseline-admin-network-policy-extended-ingress-rules.go
Labels: kind/bug, cncf-cla: yes, size/L, approved, lgtm, area/conformance

#219 Ensure we clarify subjects don't include host-net pods
  apis/v1alpha1/adminnetworkpolicy_types.go
  apis/v1alpha1/baselineadminnetworkpolicy_types.go
  config/crd/experimental/policy.networking.k8s.io_adminnetworkpolicies.yaml
  config/crd/experimental/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
  config/crd/standard/policy.networking.k8s.io_adminnetworkpolicies.yaml
  config/crd/standard/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS

#224 add ci for conformance tests
  .github/workflows/conformance.yml
Labels: cncf-cla: yes, size/L, approved, lgtm
