Repository kubernetes-sigs/network-policy-api, pull requests merged in 2024-01, with the labels that each got.

#184 Correct typo from 'protocall' to 'protocol'
  docs/legacydocs/stories/pod_reachability_query.md
Labels: cncf-cla: yes, approved, lgtm, size/XS, ok-to-test

#134 NPEP: FQDN Selector for Egress, User stories
  .gitignore
  mkdocs.yml
  npeps/npep-133.md
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#144 NPEP: Iron out Cluster Egress Support API Design
  mkdocs.yml
  npeps/npep-126-egress-traffic-control.md
Labels: cncf-cla: yes, size/L, approved, lgtm, api-review
