Repository kubernetes-sigs/network-policy-api, pull requests merged in 2024-03, with the labels that each got.

#185 Implement inline CIDR block egress peer
  apis/v1alpha1/shared_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/experimental/policy.networking.k8s.io_adminnetworkpolicies.yaml
  config/crd/experimental/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
  mkdocs.yml
  npeps/npep-126-egress-traffic-control.md
  npeps/npep-137-conformance-profiles.md
  site-src/npeps/npep-126-egress-traffic-control.md
  site-src/npeps/npep-137-conformance-profiles.md
Labels: cncf-cla: yes, size/L, approved, lgtm

#206 [Policy Assistant] add huntergregory to OWNERS
  cmd/policy-assistant/OWNERS
Labels: cncf-cla: yes, approved, lgtm, size/XS

#188 Add support for ANP and BANP in the explain command
  cmd/policy-assistant/examples/example.go
  cmd/policy-assistant/pkg/cli/analyze.go
  cmd/policy-assistant/pkg/kube/labelselector.go
  cmd/policy-assistant/pkg/matcher/builder.go
  cmd/policy-assistant/pkg/matcher/builder_tests.go
  cmd/policy-assistant/pkg/matcher/explain.go
  cmd/policy-assistant/pkg/matcher/peermatcherv2.go
  cmd/policy-assistant/pkg/matcher/portmatcher.go
  cmd/policy-assistant/pkg/matcher/target.go
  cmd/policy-assistant/test/integration/explain_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL, ok-to-test

#207 Run experimental CRD installs in CI
  Makefile
  config/crd/experimental/kustomization.yaml
  config/crd/experimental/kustomizeconfig.yaml
  config/crd/standard/kustomization.yaml
  config/crd/standard/kustomizeconfig.yaml
  hack/crd-e2e.sh
Labels: cncf-cla: yes, size/M

#209 Add kubebuilder syntax for status.conditions
  apis/v1alpha1/adminnetworkpolicy_types.go
  apis/v1alpha1/baselineadminnetworkpolicy_types.go
  config/crd/experimental/policy.networking.k8s.io_adminnetworkpolicies.yaml
  config/crd/experimental/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
  config/crd/standard/policy.networking.k8s.io_adminnetworkpolicies.yaml
  config/crd/standard/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
  hack/update-codegen.sh
  pkg/client/applyconfiguration/apis/v1alpha1/adminnetworkpolicy.go
  pkg/client/applyconfiguration/apis/v1alpha1/adminnetworkpolicyegresspeer.go
  pkg/client/applyconfiguration/apis/v1alpha1/adminnetworkpolicyegressrule.go
  pkg/client/applyconfiguration/apis/v1alpha1/adminnetworkpolicyingresspeer.go
  pkg/client/applyconfiguration/apis/v1alpha1/adminnetworkpolicyingressrule.go
  pkg/client/applyconfiguration/apis/v1alpha1/adminnetworkpolicyport.go
  pkg/client/applyconfiguration/apis/v1alpha1/adminnetworkpolicyspec.go
  pkg/client/applyconfiguration/apis/v1alpha1/adminnetworkpolicystatus.go
  pkg/client/applyconfiguration/apis/v1alpha1/adminnetworkpolicysubject.go
  pkg/client/applyconfiguration/apis/v1alpha1/baselineadminnetworkpolicy.go
  pkg/client/applyconfiguration/apis/v1alpha1/baselineadminnetworkpolicyegressrule.go
  pkg/client/applyconfiguration/apis/v1alpha1/baselineadminnetworkpolicyingressrule.go
  pkg/client/applyconfiguration/apis/v1alpha1/baselineadminnetworkpolicyspec.go
  pkg/client/applyconfiguration/apis/v1alpha1/baselineadminnetworkpolicystatus.go
  pkg/client/applyconfiguration/apis/v1alpha1/namespacedpeer.go
  pkg/client/applyconfiguration/apis/v1alpha1/namespacedpodpeer.go
  pkg/client/applyconfiguration/apis/v1alpha1/namespacedpodsubject.go
  pkg/client/applyconfiguration/apis/v1alpha1/port.go
  pkg/client/applyconfiguration/apis/v1alpha1/portrange.go
  pkg/client/applyconfiguration/internal/internal.go
  pkg/client/applyconfiguration/utils.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/adminnetworkpolicy.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/baselineadminnetworkpolicy.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/fake/fake_adminnetworkpolicy.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/fake/fake_baselineadminnetworkpolicy.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#196 Remove same-not-same-labels
  apis/v1alpha1/shared_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/experimental/policy.networking.k8s.io_adminnetworkpolicies.yaml
  config/crd/experimental/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
  config/crd/standard/policy.networking.k8s.io_adminnetworkpolicies.yaml
  config/crd/standard/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
  conformance/utils/suite/conformance_profiles.go
  conformance/utils/suite/features.go
  pkg/client/applyconfiguration/apis/v1alpha1/adminnetworkpolicyegresspeer.go
  pkg/client/applyconfiguration/apis/v1alpha1/adminnetworkpolicyingresspeer.go
  pkg/client/applyconfiguration/apis/v1alpha1/adminnetworkpolicysubject.go
  pkg/client/applyconfiguration/apis/v1alpha1/namespacedpod.go
  pkg/client/applyconfiguration/utils.go
  pkg/generator/main.go
  site-src/user-story-examples/user-story-4-v1.yaml
  site-src/user-story-examples/user-story-4-v2.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#213 Add validation for ANP/BANP Enum actions
  apis/v1alpha1/adminnetworkpolicy_types.go
  apis/v1alpha1/baselineadminnetworkpolicy_types.go
  config/crd/experimental/policy.networking.k8s.io_adminnetworkpolicies.yaml
  config/crd/experimental/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
  config/crd/standard/policy.networking.k8s.io_adminnetworkpolicies.yaml
  config/crd/standard/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M
