Repository kubernetes-sigs/network-policy-api, pull requests merged in 2025-04, with the labels that each got.

#278 Fix site-src docs: Running `make docs` seems to generate some missing NPEPs
  site-src/npeps/npep-133-fqdn-egress-selector.md
Labels: cncf-cla: yes, size/L, approved, lifecycle/stale, lgtm

#293 Clarify API docs about priority conflicts
  apis/v1alpha1/adminnetworkpolicy_types.go
  config/crd/experimental/policy.networking.k8s.io_adminnetworkpolicies.yaml
  config/crd/standard/policy.networking.k8s.io_adminnetworkpolicies.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#284 Remove extended fields support
  apis/v1alpha1/adminnetworkpolicy_types.go
  apis/v1alpha1/baselineadminnetworkpolicy_types.go
  apis/v1alpha1/shared_types.go
  config/crd/experimental/policy.networking.k8s.io_adminnetworkpolicies.yaml
  config/crd/experimental/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
  config/crd/standard/policy.networking.k8s.io_adminnetworkpolicies.yaml
  config/crd/standard/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
  conformance/apis/v1alpha1/profilereport.go
  conformance/base/admin_network_policy/experimental-egress-selector-rules.yaml
  conformance/base/admin_network_policy/standard-egress-sctp-rules.yaml
  conformance/base/admin_network_policy/standard-egress-tcp-rules.yaml
  conformance/base/admin_network_policy/standard-egress-udp-rules.yaml
  conformance/base/admin_network_policy/standard-gress-rules-combined.yaml
  conformance/base/admin_network_policy/standard-ingress-sctp-rules.yaml
  conformance/base/admin_network_policy/standard-ingress-tcp-rules.yaml
  conformance/base/admin_network_policy/standard-ingress-udp-rules.yaml
  conformance/base/admin_network_policy/standard-priority-field.yaml
  conformance/base/api_integration/standard-anp-np-banp.yaml
  conformance/base/baseline_admin_network_policy/experimental-egress-selector-rules.yaml
  conformance/base/baseline_admin_network_policy/standard-egress-sctp-rules.yaml
  conformance/base/baseline_admin_network_policy/standard-egress-tcp-rules.yaml
  conformance/base/baseline_admin_network_policy/standard-egress-udp-rules.yaml
  conformance/base/baseline_admin_network_policy/standard-gress-rules-combined.yaml
  conformance/base/baseline_admin_network_policy/standard-ingress-sctp-rules.yaml
  conformance/base/baseline_admin_network_policy/standard-ingress-tcp-rules.yaml
  conformance/base/baseline_admin_network_policy/standard-ingress-udp-rules.yaml
  conformance/tests/admin-network-policy-experimental-egress-rules.go
  conformance/tests/admin-network-policy-experimental-ingress-rules.go
  conformance/tests/admin-network-policy-standard-egress-sctp-rules.go
  conformance/tests/admin-network-policy-standard-egress-tcp-rules.go
  conformance/tests/admin-network-policy-standard-egress-udp-rules.go
  conformance/tests/admin-network-policy-standard-gress-rules.go
  conformance/tests/admin-network-policy-standard-ingress-sctp-rules.go
  conformance/tests/admin-network-policy-standard-ingress-tcp-rules.go
  conformance/tests/admin-network-policy-standard-ingress-udp-rules.go
  conformance/tests/admin-network-policy-standard-integration.go
  conformance/tests/admin-network-policy-standard-priority.go
  conformance/tests/baseline-admin-network-policy-experimental-egress-rules.go
  conformance/tests/baseline-admin-network-policy-experimental-ingress-rules.go
  conformance/tests/baseline-admin-network-policy-standard-egress-sctp-rules.go
  conformance/tests/baseline-admin-network-policy-standard-egress-tcp-rules.go
  conformance/tests/baseline-admin-network-policy-standard-egress-udp-rules.go
  conformance/tests/baseline-admin-network-policy-standard-gress-rules.go
  conformance/tests/baseline-admin-network-policy-standard-ingress-sctp-rules.go
  conformance/tests/baseline-admin-network-policy-standard-ingress-tcp-rules.go
  conformance/tests/baseline-admin-network-policy-standard-ingress-udp-rules.go
  conformance/utils/suite/conformance_profiles.go
  conformance/utils/suite/conformance_reports.go
  conformance/utils/suite/conformance_suite.go
  conformance/utils/suite/features.go
  conformance/utils/suite/suite.go
  npeps/npep-126-egress-traffic-control.md
  npeps/npep-137-conformance-profiles.md
  site-src/npeps/npep-126-egress-traffic-control.md
  site-src/npeps/npep-137-conformance-profiles.md
Labels: cncf-cla: yes, approved, size/XL, lgtm

#298 Fix IPv6 CI by bumping Ubuntu image
  .github/workflows/conformance.yml
Labels: cncf-cla: yes, approved, lgtm, size/XS
